apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: demo-python-03241631
spec:
  replicas: 1 
  template: 
    spec:
      containers:
        - image: quay.io/roming22-org/public:ce2503c8d8995ceb2e3ced55cff785d69cfde821
          name: container-image
